### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by ChildishGiant** [bluesabre/darkbar#3]
I'd love an option to just make all apps (Including ones opened for the first time) use the same option, in my case "Follow System Theme"

**Comment by bluesabre** [comment]
Yes, that definitely makes sense. I'll make it happen with the next release!

**Comment by bluesabre** [comment]
I added this feature with the above commit. Thanks for the suggestion!

![Screenshot from 2021-11-08 20-42-33](https://user-images.githubusercontent.com/1894517/140846266-449194a8-2ff2-4ff7-8e5f-04a4d2bca56f.png)
