### ISSUE TITLE
Support for 1Password

### ISSUE THREAD

**Issue by dling** [bluesabre/darkbar#4]
Would be super happy if support for dark mode in the 1Password application could be looked into.  I see 1Password working dark mode on other Ubuntu-based distros such as Pop OS, but cant get it to be dark themed in Elementary even with this tool.

Thanks

**Comment by cassidyjames** [comment]
This tool only affects the titlebars of apps but cannot change the app behavior itself. You'd need to open and issue with 1Password to support the elementary OS dark style preference (which we're also pushing for with GNOME, GTK, and FreeDesktop).

**Comment by bluesabre** [comment]
Cassidy is correct. Closing this issue out.
