### ISSUE TITLE
Doesn't resepect custom window controls layout

### ISSUE THREAD

**Issue by ChildishGiant** [bluesabre/darkbar#6]
![image](https://user-images.githubusercontent.com/13716824/131670022-59f2beb2-4f03-4c8a-951e-c6bada70fa2c.png)
![image](https://user-images.githubusercontent.com/13716824/131669997-513195e8-aadd-4283-8181-ef207665e960.png)

**Comment by bluesabre** [comment]
Should be resolved with the above commit!
