### ISSUE TITLE
App launcher not visible in Applications Launcher (slingshot)

### ISSUE THREAD

**Issue by Eldhrimer** [bluesabre/darkbar#7]
After installing through Appcenter in elementary 6 Odin, the app launcher is not available in the Applications menu (slingshot).
However searching for the App will show it in the results.

This was confirmed in both my laptop and my desktop running elementary OS 6 Odin.

I believe this behavior is not intended.

**Comment by ChildishGiant** [comment]
Pretty sure this in an issue with slingshot, not darkbar.

**Comment by NathanBnm** [comment]
May be fixed by #9 Need to check

**Comment by bluesabre** [comment]
If it shows in search but not in the list, this would be an issue with slingshot. Closing this one out.
